name: Build OpenBlueFilter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Display Python version
      run: |
        python --version
        python -c "import sys; print(sys.executable)"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        # Install any additional dependencies if needed
        pip install PyQt6
        
    - name: List installed packages
      run: |
        pip list
        
    - name: Verify file structure
      run: |
        dir
        dir src
        
    - name: Verify imports
      run: |
        python -c "import src; print('Base import successful')"
        python -c "try: import src.main; print('Main import successful'); except Exception as e: print(f'Error: {e}')"
      continue-on-error: true  # Don't fail the whole workflow if this fails
        
    - name: Build executable
      run: |
        python build_fix.py
      
    - name: Verify build output
      run: |
        dir dist
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OpenBlueFilter-Windows
        path: dist/OpenBlueFilter.exe 